### ISSUE TITLE
how to send from taproot address to another taproot address?

### ISSUE THREAD

**Issue by viponedream** [karask/python-bitcoin-utils#109]
examples/spend_p2tr_default_path.py
   # UTXO of fromAddress
    txid = "7b6412a0eed56338731e83c606f13ebb7a3756b3e4e1dbbe43a7db8d09106e56"
    vout = 1

the txid is? where to find this  7b6412a0eed56338731e83c606f13ebb7a3756b3e4e1dbbe43a7db8d09106e56?
help!

**Comment by karask** [comment]
You need some input to spend. You can either find those programmatically with the proxy object (see example) to get the UTXOs of a node, etc. Then, you need to select a UTXO that was locked using taproot (without a script) and then that example applies.

If the taproot was locked with a script there are other examples. In those cases, in order to spend you also need to know the structure of the locking scripts.

You need to understand better how taproot works to use the examples properly. If you don't have experience with bitcoin in general, I would recommend starting with legacy transactions (P2PKH, P2SH) and then going into segwit/taproot ones.

Hope this helped.
