### ISSUE TITLE
spend_p2wpkh output

### ISSUE THREAD

**Issue by mrx23dot** [karask/python-bitcoin-utils#31]
I ran `examples\spend_p2wpkh_transaction.py`

It created raw signed transaction:
`02000000000101ff67938803c97f765e89dfe81522a20569a38f60b911daa58f4e97ca0ed3d2130000000000ffffffff01a0bb0d00000000001976a9147c52f8c1f6b885f8dd677365232f2e92b368fa2388ac02483045022100debdd831b8f144afcaa4e9cb71713ec657292ac09d163e827dc1d458417841a70220292b6f250e4ad94ec2b3f062129b85620c22be9be97f8a42346612de8fc423200121028b9b0e596dbefb2055c0bfd7bb34b90d491030df81a2659ca5dbf941647e28ea00000000`

Then inputed this to: https://coinb.in/#verify  (don't forget to set testnet under help/settings)
it says Transaction Size: 195 bytes  -> which seems big (close to p2pkh's), should be around 105 bytes with 1input+1output.

also script part couldn't be decoded:
![2022-09-17_155720_HA](https://user-images.githubusercontent.com/4163396/190863342-d821852e-7c54-4e7e-b501-b8565d151152.jpg)

Then I recreated the original intent on this site and signed it which gave
`0100000001ff67938803c97f765e89dfe81522a20569a38f60b911daa58f4e97ca0ed3d213000000006a473044022029ca3e931f5a0599b7a6743b1972daf568bf94bfb66f18e1350347d21599779102204bc8fde424e5af996369b5f675bce285f140a16d0454339b182b27b57424f02d0121028b9b0e596dbefb2055c0bfd7bb34b90d491030df81a2659ca5dbf941647e28eafeffffff01a0bb0d00000000001976a9147c52f8c1f6b885f8dd677365232f2e92b368fa2388ac00000000`

decoding it 
![2022-09-17_160825_DR](https://user-images.githubusercontent.com/4163396/190863865-1bd7f756-b067-496e-a1b1-f757fd50a539.jpg)
- it fills script unlike this lib
- it's v1 transaction not sure if that counts
- not sure why it's still 191bytes, the goal bech32 was to save space

Comparing the 2 hexes there are significant differences, also note website says signed, but doesn't actually verifies it.

Is there a wrapper lib that can transfer from any kind of address? (selecting the correct method in the background)

**Comment by karask** [comment]
Hi @mrx23dot 

Version 1 means that timelocks are not permited (BIP-68). Transactions are typically version 2 now, although nothing is wrong with v1 if you don't use BIP-68.

In segwit the actual size of the transaction (raw bytes) does not change by much. The virtual size (the one that counts towards the 1MB limit) is reduced. The 'effective or virtual' size is smaller because we move the signature out of the transaction... but the signature is still transmitted to the node, thus the actual size sent is still 195.

Add:
print(tx.get_size())
print(tx.get_vsize())

To see the actual size (raw bytes) and virtual size respectively.

Use the following calculator for more detailed results depending on the type of transactions:
https://jlopp.github.io/bitcoin-transaction-size-calculator/

Hope this helps
