### ISSUE TITLE
spend_p2sh example fails

### ISSUE THREAD

**Issue by mrx23dot** [karask/python-bitcoin-utils#32]
Hi,
I'm trying to run examples\spend_p2sh_transaction.py
but when I try to broadcast the signed transaction I get back:

```
'code': -26
'message': 'mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)'
```

Stackoverflow suggests there is something wrong with the signing (like one field has to be zeroed while signing other field).

config:  (in: 1*3xx, out: 1*1xx address)
from 3LNAAKJmuv7ZrFLcmUif5cAZwEvj7J8a8g
to 1B8unyP6dqLq2k5wn7RHQuLeQF87SWyfws

```
txin = TxInput('c34279de38a03b744c79e14eb71528c5b026be4e18c1f88b265c66a4bc55ff88', 0)
to_addr = P2pkhAddress('1B8unyP6dqLq2k5wn7RHQuLeQF87SWyfws')
txout = TxOutput(to_satoshis(0.00000985), to_addr.to_script_pub_key() )
```

**Comment by karask** [comment]
Hi @mrx23dot 

The `txin.script_sig'` part updates the unlocking script with the new signature. Objects in python are passed by reference.

Is the redeem script you are using P2PK? 

If yes, I will need to investigate more. 

It would help me If you can simulate an example in testnet (create a P2PK output and share the key) so that I can try it out.

**Comment by karask** [comment]
Got the email. I won't have time to look at it today.

Until I do though, note that the example tries to spend a P2SH locking script that contains a P2PK (not P2PKH or segwit) redeem script. If the redeem script is not a P2PK script, it is expected to fail.

All, P2SH scripts start with 3 (or 2 in testnet) regardless of what they contain.
The example script is a P2SH(P2PK) script.
A nested segwit is a P2SH(P2WPKH or P2WSH).
A native segwit starts with bc1.

Hope the above helps

**Comment by karask** [comment]
I don't know about such a wrapper. 

So, in order to spend a P2SH you need to know the redeem script. If we know the redeem script and we have the appropriate private key we can modify the example script to spend it without any issues.

The only person that knows the redeem script is the person that created the P2SH address. 

If the redeem script is P2PK then the example should be working and I will try to see what went wrong.

Just give me the redeem script, exactly as used to create the P2SH address, and we'll spend it :-)

**Comment by karask** [comment]
This is the locking script of a P2SH. It can contain _any_ arbitrary Bitcoin script. The contained script is called redeem script. Only the person that knows the redeem script can spend the funds.

If you know the private key you could try to spend it as P2SH(P2WPKH) or as P2SH(P2PK). But it could be an arbitrary script, so no luck there.

I am closing this issue as it seems it is not related to the library.
