### ISSUE TITLE
"Non-mandatory-script-verify-flag error: Invalid Schnorr signature" occurred with two different inputs (P2TR + P2WSH or P2SH) Signet.

### ISSUE THREAD

**Issue by MohsenHaydari** [karask/python-bitcoin-utils#48]
Hi
Signet also experiences the same issue when attempting to spend two inputs (P2TR + P2SH or P2WPKH).
I have prepared two scripts for this transaction type, and both of them are encountering errors. If possible, please review both scripts to identify potential issues. Thank you.

[spend_p2tr_p2wpkh_to_p2pkh.py](https://github.com/MohsenHaydari/bitcoin_base/blob/main/spend_p2tr_p2wpkh_to_p2pkh.py)
[spend_p2tr_p2sh_to_p2pkh.py](https://github.com/MohsenHaydari/bitcoin_base/blob/main/spend_p2tr_p2sh_to_p2pkh.py)

**Comment by karask** [comment]
Hi Mohsen,

I had a look at the first one.

Since it is a segwit address you should use get_segwit_address in line 21.

Also, while taproot (segwit v1) requires the scriptPubKey when signing, segwit v0 requires the script code; i.e. a template that corresponds to the non-segwit equivalent. For example, for p2wpkh you would use as script code the p2pkh scriptPubKey.

So when signing the segwit input you shouldn't use the scriptPubKey but the corresponding p2pkh template for that address. Example https://github.com/karask/python-bitcoin-utils/blob/master/examples/spend_p2wpkh_transaction.py demonstrates this.

I haven't tried it out the above, but will do with the first opportunity.

PS. In the meantime, if you try it out yourself please use ```testmempoolaccept``` to test tx validity instead of just sending the tx to a node for processing. That will test tx validity without spending the outputs. If there is still an issue I can then test using the same UTXOs.

**Comment by karask** [comment]
Just tried it and it works. Closing the issue but let me know if you need further help.

**Comment by MohsenHaydari** [comment]
Thanks, it will take me a while to graduate to Bitcoin. :D

**Comment by karask** [comment]
This was a tricky one. It seems to me that you are doing fine!

**Comment by MohsenHaydari** [comment]
> This was a tricky one. It seems to me that you are doing fine!

Your package is truly exceptional. 
I've successfully sent this transaction using the Dart package. [https://mempool.space/testnet/tx/ffb96b60303eb8e76654d320204a2727dec57ca00cf947a50c2be40ff084e35e](mempol)
I've created a Dart script that automatically detects transactions and generates the output.
 I plan to translate it to Python at the earliest opportunity. Perhaps you'd be interested in including it in your package
Thanks

**Comment by karask** [comment]
Thank you for your kind words. I have deliberately not included a lot of conveniences like that. The reason being that I primarily use the library for teaching purposes and want the students to have to deal with some of the low level stuff.

Having said that, I would be happy to consider such automations if they are well-defined, in their own files (or maybe inside utils.py) and do not influence the existing codebase (i.e. are optional). 

If you find the time you can add an issue with the suggested methods/changes at a high level and discuss them or of course you can do a PR and we can take it from there.
